"""
Simple example showing how to create an Exodus mesh using the builder API.
"""

try:
    from exodus import MeshBuilder, BlockBuilder

    print("Creating a simple 2D quad mesh...")

    # Create a 2D quad mesh using the fluent builder API
    (MeshBuilder("Simple Quad Mesh")
        .dimensions(2)
        .coordinates(
            x=[0.0, 1.0, 1.0, 0.0],
            y=[0.0, 0.0, 1.0, 1.0],
            z=[]
        )
        .add_block(
            BlockBuilder(1, "QUAD4")
                .connectivity([1, 2, 3, 4])
                .build()
        )
        .qa_record("exodus-py", "0.1.0", "2025-01-15", "12:00:00")
        .info("Generated by simple_mesh.py example")
        .write("/tmp/simple_quad.exo"))

    print("✓ Created /tmp/simple_quad.exo")

    # Create a 3D hex mesh
    print("\nCreating a 3D hex mesh...")

    (MeshBuilder("Single Hex Element")
        .dimensions(3)
        .coordinates(
            x=[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0],
            y=[0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0],
            z=[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0]
        )
        .add_block(
            BlockBuilder(100, "HEX8")
                .connectivity([1, 2, 3, 4, 5, 6, 7, 8])
                .attributes([1.0])
                .attribute_names(["MaterialID"])
                .build()
        )
        .write("/tmp/single_hex.exo"))

    print("✓ Created /tmp/single_hex.exo")

    print("\n✅ All meshes created successfully!")
    print("\nTo read the mesh:")
    print("    from exodus import ExodusReader")
    print("    with ExodusReader.open('/tmp/simple_quad.exo') as reader:")
    print("        params = reader.init_params()")
    print("        print(f'Nodes: {params.num_nodes}')")

except ImportError as e:
    print(f"❌ Failed to import exodus module: {e}")
    print("\nTo build and install:")
    print("    cd rust/exodus-py")
    print("    pip install maturin")
    print("    maturin develop")
except Exception as e:
    print(f"❌ Error: {e}")
    import traceback
    traceback.print_exc()
