"""
Type stubs for exodus Rust extension module.

This file provides type hints for the exodus Python bindings to the exodus-rs library.
"""

from typing import List, Optional, Tuple, Any, Union
from types import TracebackType

__version__: str

# Enumerations

class EntityType:
    """Entity types in Exodus II"""
    ElemBlock: EntityType
    NodeSet: EntityType
    SideSet: EntityType
    NodeMap: EntityType
    ElemMap: EntityType
    EdgeBlock: EntityType
    EdgeSet: EntityType
    FaceBlock: EntityType
    FaceSet: EntityType
    ElemSet: EntityType
    EdgeMap: EntityType
    FaceMap: EntityType
    Global: EntityType
    Nodal: EntityType
    Assembly: EntityType
    Blob: EntityType

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class CreateMode:
    """File creation mode"""
    Clobber: CreateMode
    NoClobber: CreateMode

    def __str__(self) -> str: ...

class FloatSize:
    """Floating point precision"""
    Float32: FloatSize
    Float64: FloatSize

    def __str__(self) -> str: ...

class Int64Mode:
    """Integer storage mode"""
    Int32: Int64Mode
    Int64: Int64Mode

    def __str__(self) -> str: ...

class AttributeType:
    """Attribute value type"""
    Integer: AttributeType
    Double: AttributeType
    Char: AttributeType

    def __str__(self) -> str: ...

# Performance Configuration

class NodeType:
    """Node type detection for HPC environments"""

    @staticmethod
    def detect() -> NodeType: ...

    @staticmethod
    def compute() -> NodeType: ...

    @staticmethod
    def login() -> NodeType: ...

    @staticmethod
    def unknown() -> NodeType: ...

    def default_cache_size(self) -> int: ...
    def default_chunk_nodes(self) -> int: ...
    def default_chunk_elements(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CacheConfig:
    """HDF5 chunk cache configuration"""

    def __init__(
        self,
        cache_size: Optional[int] = None,
        num_slots: int = 0,
        preemption: float = 0.75
    ) -> None: ...

    def with_cache_size(self, size: int) -> CacheConfig: ...
    def with_cache_mb(self, mb: int) -> CacheConfig: ...
    def with_slots(self, num_slots: int) -> CacheConfig: ...
    def with_preemption(self, preemption: float) -> CacheConfig: ...

    @property
    def cache_size(self) -> int: ...

    @property
    def num_slots(self) -> int: ...

    @property
    def preemption(self) -> float: ...

    def __repr__(self) -> str: ...

class ChunkConfig:
    """NetCDF/HDF5 chunking configuration"""

    def __init__(
        self,
        chunk_nodes: Optional[int] = None,
        chunk_elements: Optional[int] = None
    ) -> None: ...

    def with_chunk_nodes(self, size: int) -> ChunkConfig: ...
    def with_chunk_elements(self, size: int) -> ChunkConfig: ...

    @property
    def chunk_nodes(self) -> int: ...

    @property
    def chunk_elements(self) -> int: ...

    def __repr__(self) -> str: ...

class PerformanceConfig:
    """Complete performance configuration"""

    def __init__(
        self,
        cache: Optional[CacheConfig] = None,
        chunking: Optional[ChunkConfig] = None
    ) -> None: ...

    @staticmethod
    def detect() -> PerformanceConfig: ...

    @staticmethod
    def default() -> PerformanceConfig: ...

    @staticmethod
    def for_compute_node() -> PerformanceConfig: ...

    @staticmethod
    def for_login_node() -> PerformanceConfig: ...

    def with_cache(self, cache: CacheConfig) -> PerformanceConfig: ...
    def with_chunking(self, chunking: ChunkConfig) -> PerformanceConfig: ...
    def __repr__(self) -> str: ...

# Data Types

class InitParams:
    """Initialization parameters for Exodus database"""

    title: str
    num_dim: int
    num_nodes: int
    num_edges: int
    num_edge_blocks: int
    num_faces: int
    num_face_blocks: int
    num_elems: int
    num_elem_blocks: int
    num_node_sets: int
    num_edge_sets: int
    num_face_sets: int
    num_side_sets: int
    num_elem_sets: int
    num_node_maps: int
    num_edge_maps: int
    num_face_maps: int
    num_elem_maps: int
    num_assemblies: int
    num_blobs: int

    def __init__(
        self,
        title: str = "",
        num_dim: int = 3,
        num_nodes: int = 0,
        num_elems: int = 0,
        num_elem_blocks: int = 0,
        **kwargs: int
    ) -> None: ...

    def __repr__(self) -> str: ...

class CreateOptions:
    """File creation options"""

    mode: CreateMode
    float_size: FloatSize
    int64_mode: Int64Mode
    performance: Optional[PerformanceConfig]

    def __init__(
        self,
        mode: CreateMode = ...,
        float_size: FloatSize = ...,
        int64_mode: Int64Mode = ...,
        performance: Optional[PerformanceConfig] = None
    ) -> None: ...

    def __repr__(self) -> str: ...

class Block:
    """Element/Edge/Face block definition"""

    id: int
    entity_type: EntityType
    topology: str
    num_entries: int
    num_nodes_per_entry: int
    num_edges_per_entry: int
    num_faces_per_entry: int
    num_attributes: int

    def __init__(
        self,
        id: int,
        entity_type: EntityType,
        topology: str,
        num_entries: int,
        num_nodes_per_entry: int,
        num_edges_per_entry: int = 0,
        num_faces_per_entry: int = 0,
        num_attributes: int = 0
    ) -> None: ...

    def __repr__(self) -> str: ...

class NodeSet:
    """Node set definition"""

    id: int
    nodes: List[int]
    dist_factors: List[float]

    def __init__(
        self,
        id: int,
        nodes: List[int],
        dist_factors: List[float] = ...
    ) -> None: ...

    def __repr__(self) -> str: ...

class SideSet:
    """Side set definition"""

    id: int
    elements: List[int]
    sides: List[int]
    dist_factors: List[float]

    def __init__(
        self,
        id: int,
        elements: List[int],
        sides: List[int],
        dist_factors: List[float] = ...
    ) -> None: ...

    def __repr__(self) -> str: ...

class EntitySet:
    """Entity set (edge, face, or element set)"""

    id: int
    entity_type: EntityType
    entities: List[int]

    def __init__(
        self,
        id: int,
        entity_type: EntityType,
        entities: List[int]
    ) -> None: ...

    def __repr__(self) -> str: ...

class Assembly:
    """Assembly (hierarchical grouping)"""

    id: int
    name: str
    entity_type: EntityType
    entity_list: List[int]

    def __init__(
        self,
        id: int,
        name: str,
        entity_type: EntityType,
        entity_list: List[int]
    ) -> None: ...

    def __repr__(self) -> str: ...

class Blob:
    """Blob (arbitrary binary data)"""

    id: int
    name: str

    def __init__(self, id: int, name: str) -> None: ...
    def __repr__(self) -> str: ...

class QaRecord:
    """QA record for provenance tracking"""

    code_name: str
    code_version: str
    date: str
    time: str

    def __init__(
        self,
        code_name: str,
        code_version: str,
        date: str,
        time: str
    ) -> None: ...

    def __repr__(self) -> str: ...

class TruthTable:
    """Truth table for sparse variable storage"""

    @property
    def var_type(self) -> EntityType: ...

    @property
    def num_vars(self) -> int: ...

    @property
    def num_blocks(self) -> int: ...

    @staticmethod
    def new(var_type: EntityType, num_blocks: int, num_vars: int) -> TruthTable: ...

    def set(self, block_idx: int, var_idx: int, exists: bool) -> None: ...
    def get(self, block_idx: int, var_idx: int) -> bool: ...
    def __repr__(self) -> str: ...

class AttributeData:
    """Attribute data wrapper"""

    @staticmethod
    def integer(values: List[int]) -> AttributeData: ...

    @staticmethod
    def double(values: List[float]) -> AttributeData: ...

    @staticmethod
    def char(value: str) -> AttributeData: ...

    def as_integer(self) -> List[int]: ...
    def as_double(self) -> List[float]: ...
    def as_char(self) -> str: ...
    def __repr__(self) -> str: ...

# File Classes

class ExodusReader:
    """Exodus file reader (read-only access)"""

    @staticmethod
    def open(path: str) -> ExodusReader: ...

    def init_params(self) -> InitParams: ...
    def path(self) -> str: ...
    def version(self) -> Tuple[int, int]: ...
    def format(self) -> str: ...
    def close(self) -> None: ...

    # Coordinate operations
    def coordinates(self) -> Tuple[List[float], List[float], List[float]]: ...
    def coordinate_names(self) -> List[str]: ...

    # Block operations
    def blocks(self, entity_type: EntityType) -> List[Block]: ...
    def block_ids(self, entity_type: EntityType) -> List[int]: ...
    def block(self, entity_type: EntityType, block_id: int) -> Block: ...
    def block_name(self, entity_type: EntityType, block_id: int) -> str: ...
    def connectivity(self, entity_type: EntityType, block_id: int) -> List[int]: ...

    # Set operations
    def node_sets(self) -> List[NodeSet]: ...
    def node_set_ids(self) -> List[int]: ...
    def node_set(self, set_id: int) -> NodeSet: ...
    def node_set_name(self, set_id: int) -> str: ...

    def side_sets(self) -> List[SideSet]: ...
    def side_set_ids(self) -> List[int]: ...
    def side_set(self, set_id: int) -> SideSet: ...
    def side_set_name(self, set_id: int) -> str: ...

    def entity_sets(self, entity_type: EntityType) -> List[EntitySet]: ...
    def entity_set_ids(self, entity_type: EntityType) -> List[int]: ...
    def entity_set(self, entity_type: EntityType, set_id: int) -> EntitySet: ...
    def entity_set_name(self, entity_type: EntityType, set_id: int) -> str: ...

    # Map operations
    def node_map(self, map_id: int = 0) -> List[int]: ...
    def element_map(self, map_id: int = 0) -> List[int]: ...
    def map(self, entity_type: EntityType, map_id: int = 0) -> List[int]: ...

    # Metadata operations
    def title(self) -> str: ...
    def qa_records(self) -> List[QaRecord]: ...
    def info_records(self) -> List[str]: ...

    # Variable operations
    def global_variable_names(self) -> List[str]: ...
    def nodal_variable_names(self) -> List[str]: ...
    def variable_names(self, entity_type: EntityType) -> List[str]: ...

    def num_time_steps(self) -> int: ...
    def time_values(self) -> List[float]: ...

    def global_variable_values(self, var_name: str) -> List[float]: ...
    def nodal_variable_values(self, var_name: str, time_step: int) -> List[float]: ...
    def element_variable_values(self, var_name: str, block_id: int, time_step: int) -> List[float]: ...
    def variable_values(
        self,
        entity_type: EntityType,
        var_name: str,
        entity_id: int,
        time_step: int
    ) -> List[float]: ...

    def truth_table(self, entity_type: EntityType) -> TruthTable: ...

    # Attribute operations
    def get_attribute(
        self,
        entity_type: EntityType,
        entity_id: int,
        name: str
    ) -> AttributeData: ...

    def get_attribute_names(
        self,
        entity_type: EntityType,
        entity_id: int
    ) -> List[str]: ...

    # Assembly operations
    def assemblies(self) -> List[Assembly]: ...
    def assembly_ids(self) -> List[int]: ...
    def assembly(self, assembly_id: int) -> Assembly: ...
    def assembly_name(self, assembly_id: int) -> str: ...

    # Blob operations
    def blobs(self) -> List[Blob]: ...
    def blob_ids(self) -> List[int]: ...
    def blob(self, blob_id: int) -> Blob: ...
    def blob_name(self, blob_id: int) -> str: ...

    # Context manager
    def __enter__(self) -> ExodusReader: ...
    def __exit__(
        self,
        exc_type: Optional[type],
        exc_value: Optional[BaseException],
        traceback: Optional[TracebackType]
    ) -> bool: ...
    def __repr__(self) -> str: ...

class ExodusWriter:
    """Exodus file writer (write-only, for creating new files)"""

    @staticmethod
    def create(path: str, options: Optional[CreateOptions] = None) -> ExodusWriter: ...

    def put_init_params(self, params: InitParams) -> None: ...
    def path(self) -> str: ...
    def sync(self) -> None: ...
    def close(self) -> None: ...

    # Coordinate operations
    def put_coordinates(
        self,
        x: List[float],
        y: List[float],
        z: List[float]
    ) -> None: ...

    def put_coordinate_names(self, names: List[str]) -> None: ...

    # Block operations
    def put_block(self, block: Block) -> None: ...
    def put_block_name(self, entity_type: EntityType, block_id: int, name: str) -> None: ...
    def put_connectivity(
        self,
        entity_type: EntityType,
        block_id: int,
        connectivity: List[int]
    ) -> None: ...

    # Set operations
    def put_node_set(self, node_set: NodeSet) -> None: ...
    def put_node_set_name(self, set_id: int, name: str) -> None: ...

    def put_side_set(self, side_set: SideSet) -> None: ...
    def put_side_set_name(self, set_id: int, name: str) -> None: ...

    def put_entity_set(self, entity_set: EntitySet) -> None: ...
    def put_entity_set_name(
        self,
        entity_type: EntityType,
        set_id: int,
        name: str
    ) -> None: ...

    # Map operations
    def put_node_map(self, node_map: List[int], map_id: int = 0) -> None: ...
    def put_element_map(self, element_map: List[int], map_id: int = 0) -> None: ...
    def put_map(
        self,
        entity_type: EntityType,
        entity_map: List[int],
        map_id: int = 0
    ) -> None: ...

    # Metadata operations
    def put_qa_record(self, qa_record: QaRecord) -> None: ...
    def put_qa_records(self, qa_records: List[QaRecord]) -> None: ...
    def put_info_records(self, info_records: List[str]) -> None: ...

    # Variable operations
    def put_global_variable_names(self, names: List[str]) -> None: ...
    def put_nodal_variable_names(self, names: List[str]) -> None: ...
    def put_variable_names(self, entity_type: EntityType, names: List[str]) -> None: ...

    def put_time(self, time_step: int, time_value: float) -> None: ...

    def put_global_variable_values(
        self,
        time_step: int,
        var_name: str,
        value: float
    ) -> None: ...

    def put_nodal_variable_values(
        self,
        time_step: int,
        var_name: str,
        values: List[float]
    ) -> None: ...

    def put_element_variable_values(
        self,
        time_step: int,
        var_name: str,
        block_id: int,
        values: List[float]
    ) -> None: ...

    def put_variable_values(
        self,
        entity_type: EntityType,
        time_step: int,
        var_name: str,
        entity_id: int,
        values: List[float]
    ) -> None: ...

    def put_truth_table(self, truth_table: TruthTable) -> None: ...

    # Attribute operations
    def put_attribute(
        self,
        entity_type: EntityType,
        entity_id: int,
        name: str,
        attr_type: AttributeType,
        data: AttributeData
    ) -> None: ...

    # Assembly operations
    def put_assembly(self, assembly: Assembly) -> None: ...
    def put_assembly_name(self, assembly_id: int, name: str) -> None: ...

    # Blob operations
    def put_blob(self, blob: Blob) -> None: ...
    def put_blob_name(self, blob_id: int, name: str) -> None: ...

    # Context manager
    def __enter__(self) -> ExodusWriter: ...
    def __exit__(
        self,
        exc_type: Optional[type],
        exc_value: Optional[BaseException],
        traceback: Optional[TracebackType]
    ) -> bool: ...
    def __repr__(self) -> str: ...

class ExodusAppender:
    """Exodus file appender (read-write access to existing files)"""

    @staticmethod
    def append(path: str) -> ExodusAppender: ...

    def init_params(self) -> InitParams: ...
    def path(self) -> str: ...
    def close(self) -> None: ...

    # Note: ExodusAppender has similar methods to ExodusWriter
    # but also supports reading operations like ExodusReader

    # Write operations (same as ExodusWriter)
    def put_coordinates(
        self,
        x: List[float],
        y: List[float],
        z: List[float]
    ) -> None: ...

    def put_coordinate_names(self, names: List[str]) -> None: ...
    def put_block(self, block: Block) -> None: ...
    def put_block_name(self, entity_type: EntityType, block_id: int, name: str) -> None: ...
    def put_connectivity(
        self,
        entity_type: EntityType,
        block_id: int,
        connectivity: List[int]
    ) -> None: ...

    def put_node_set(self, node_set: NodeSet) -> None: ...
    def put_node_set_name(self, set_id: int, name: str) -> None: ...
    def put_side_set(self, side_set: SideSet) -> None: ...
    def put_side_set_name(self, set_id: int, name: str) -> None: ...
    def put_entity_set(self, entity_set: EntitySet) -> None: ...
    def put_entity_set_name(
        self,
        entity_type: EntityType,
        set_id: int,
        name: str
    ) -> None: ...

    def put_node_map(self, node_map: List[int], map_id: int = 0) -> None: ...
    def put_element_map(self, element_map: List[int], map_id: int = 0) -> None: ...
    def put_map(
        self,
        entity_type: EntityType,
        entity_map: List[int],
        map_id: int = 0
    ) -> None: ...

    def put_qa_record(self, qa_record: QaRecord) -> None: ...
    def put_qa_records(self, qa_records: List[QaRecord]) -> None: ...
    def put_info_records(self, info_records: List[str]) -> None: ...

    def put_global_variable_names(self, names: List[str]) -> None: ...
    def put_nodal_variable_names(self, names: List[str]) -> None: ...
    def put_variable_names(self, entity_type: EntityType, names: List[str]) -> None: ...

    def put_time(self, time_step: int, time_value: float) -> None: ...
    def put_global_variable_values(
        self,
        time_step: int,
        var_name: str,
        value: float
    ) -> None: ...

    def put_nodal_variable_values(
        self,
        time_step: int,
        var_name: str,
        values: List[float]
    ) -> None: ...

    def put_element_variable_values(
        self,
        time_step: int,
        var_name: str,
        block_id: int,
        values: List[float]
    ) -> None: ...

    def put_variable_values(
        self,
        entity_type: EntityType,
        time_step: int,
        var_name: str,
        entity_id: int,
        values: List[float]
    ) -> None: ...

    def put_truth_table(self, truth_table: TruthTable) -> None: ...
    def put_assembly(self, assembly: Assembly) -> None: ...
    def put_assembly_name(self, assembly_id: int, name: str) -> None: ...
    def put_blob(self, blob: Blob) -> None: ...
    def put_blob_name(self, blob_id: int, name: str) -> None: ...

    # Read operations (limited in Append mode)
    def coordinates(self) -> Tuple[List[float], List[float], List[float]]: ...
    def coordinate_names(self) -> List[str]: ...
    def blocks(self, entity_type: EntityType) -> List[Block]: ...
    def block_ids(self, entity_type: EntityType) -> List[int]: ...
    def block(self, entity_type: EntityType, block_id: int) -> Block: ...
    def block_name(self, entity_type: EntityType, block_id: int) -> str: ...
    def connectivity(self, entity_type: EntityType, block_id: int) -> List[int]: ...

    def node_sets(self) -> List[NodeSet]: ...
    def node_set_ids(self) -> List[int]: ...
    def node_set(self, set_id: int) -> NodeSet: ...
    def node_set_name(self, set_id: int) -> str: ...

    def side_sets(self) -> List[SideSet]: ...
    def side_set_ids(self) -> List[int]: ...
    def side_set(self, set_id: int) -> SideSet: ...
    def side_set_name(self, set_id: int) -> str: ...

    def entity_sets(self, entity_type: EntityType) -> List[EntitySet]: ...
    def entity_set_ids(self, entity_type: EntityType) -> List[int]: ...
    def entity_set(self, entity_type: EntityType, set_id: int) -> EntitySet: ...
    def entity_set_name(self, entity_type: EntityType, set_id: int) -> str: ...

    def node_map(self, map_id: int = 0) -> List[int]: ...
    def element_map(self, map_id: int = 0) -> List[int]: ...
    def map(self, entity_type: EntityType, map_id: int = 0) -> List[int]: ...

    def title(self) -> str: ...
    def qa_records(self) -> List[QaRecord]: ...
    def info_records(self) -> List[str]: ...

    def global_variable_names(self) -> List[str]: ...
    def nodal_variable_names(self) -> List[str]: ...
    def variable_names(self, entity_type: EntityType) -> List[str]: ...

    def num_time_steps(self) -> int: ...
    def time_values(self) -> List[float]: ...

    def global_variable_values(self, var_name: str) -> List[float]: ...
    def nodal_variable_values(self, var_name: str, time_step: int) -> List[float]: ...
    def element_variable_values(self, var_name: str, block_id: int, time_step: int) -> List[float]: ...
    def variable_values(
        self,
        entity_type: EntityType,
        var_name: str,
        entity_id: int,
        time_step: int
    ) -> List[float]: ...

    def truth_table(self, entity_type: EntityType) -> TruthTable: ...

    # Note: Attribute read operations not available in Append mode
    def get_attribute(
        self,
        entity_type: EntityType,
        entity_id: int,
        name: str
    ) -> AttributeData: ...

    def get_attribute_names(
        self,
        entity_type: EntityType,
        entity_id: int
    ) -> List[str]: ...

    def assemblies(self) -> List[Assembly]: ...
    def assembly_ids(self) -> List[int]: ...
    def assembly(self, assembly_id: int) -> Assembly: ...
    def assembly_name(self, assembly_id: int) -> str: ...

    def blobs(self) -> List[Blob]: ...
    def blob_ids(self) -> List[int]: ...
    def blob(self, blob_id: int) -> Blob: ...
    def blob_name(self, blob_id: int) -> str: ...

    # Context manager
    def __enter__(self) -> ExodusAppender: ...
    def __exit__(
        self,
        exc_type: Optional[type],
        exc_value: Optional[BaseException],
        traceback: Optional[TracebackType]
    ) -> bool: ...
    def __repr__(self) -> str: ...

# Builder API

class BlockBuilder:
    """Fluent interface for building element blocks"""

    def __init__(self, id: int, topology: str) -> None: ...

    def connectivity(self, conn: List[int]) -> BlockBuilder: ...
    def attributes(self, attrs: List[float]) -> BlockBuilder: ...
    def attribute_names(self, names: List[str]) -> BlockBuilder: ...
    def build(self) -> BlockBuilder: ...
    def __repr__(self) -> str: ...

class MeshBuilder:
    """High-level builder for creating complete Exodus meshes"""

    def __init__(self, title: str) -> None: ...

    # Fluent API
    def dimensions(self, num_dim: int) -> MeshBuilder: ...
    def coordinates(
        self,
        x: List[float],
        y: List[float] = ...,
        z: List[float] = ...
    ) -> MeshBuilder: ...
    def add_block(self, block: BlockBuilder) -> MeshBuilder: ...
    def qa_record(
        self,
        code_name: str,
        version: str,
        date: str,
        time: str
    ) -> MeshBuilder: ...
    def info(self, info_text: str) -> MeshBuilder: ...

    # Setter API
    def set_dimensions(self, num_dim: int) -> None: ...
    def set_coordinates(
        self,
        x: List[float],
        y: List[float] = ...,
        z: List[float] = ...
    ) -> None: ...
    def add_qa_record(
        self,
        code_name: str,
        version: str,
        date: str,
        time: str
    ) -> None: ...
    def add_info(self, info: str) -> None: ...

    # Output
    def write(self, path: str) -> None: ...
    def write_with_options(self, path: str, options: CreateOptions) -> None: ...
    def __repr__(self) -> str: ...
